---
title: "Pair programming excersize"
author: "Tarrik Quneibi"
date: "2022-10-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(here)
library(knitr)
```

```{r exercise 1, include=FALSE}
gapminder_data <- read_csv('~/Desktop/tarrik-un-report/data/gapminder_data.csv') %>%
  filter(continent == 'Asia' & pop > 4e8)
```

```{r plot}
ggplot(gapminder_data, aes(x= year, y= pop, color = country)) + 
  geom_point() +
  facet_wrap(vars(continent))
```

From the population data for Asia, we found that the outlier countries are India and China.

```{r excersize 4}
gapminder_data <- read_csv('../data/gapminder_data.csv') %>%
  filter(country != "India" & country != "China")

ggplot(gapminder_data, aes(x= year, y= pop)) + 
  geom_point() +
  facet_wrap(vars(continent))


```

```{r excersize 5}
maxlife_df <- gapminder_data %>%
  filter(year == 1982) %>%
  slice_max(lifeExp)

```

Highest life expectancy is Japan

```{r excersize 8}
gapminder_data %>%
  group_by(year) %>%
  slice_max(lifeExp) %>%
  kable()


```

```{r excersize 9}
gapminder_asia <- gapminder_data %>%
  filter(continent == "Asia")


ggplot(gapminder_asia, aes(x=year, y=lifeExp, color = country))+
  geom_boxplot()


```